name: askgod
base: core22
version: git
grade: stable
summary: Askgod Scoring System - client
description: |-
 The Askgod Scoring System was written by the organizers of NorthSec.

 It's designed for Capture The Flag (CTF) type events where a number of
 teams compete on a leaderboard through points they score by sending
 "flags" to the scoring system.

 This package contains the client for the Askgod REST API and defaults
 to interacting with the on-site instance of NorthSec.

 The package also contains the server but ships in disabled mode by default.

confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

apps:
  askgod:
    command: bin/askgod
    plugs:
      - network

  discourse:
    command: bin/askgod-discourse $SNAP_COMMON/discourse.yaml
    daemon: simple
    install-mode: disable
    restart-condition: always
    restart-delay: 5s
    plugs:
      - network
      - network-bind

  server:
    command: bin/askgod-server $SNAP_COMMON/server.yaml
    daemon: simple
    install-mode: disable
    restart-condition: always
    restart-delay: 5s
    plugs:
      - network
      - network-bind

parts:
  askgod:
    source: .
    plugin: go
    build-snaps:
      - go
    prime:
      - bin/askgod
      - bin/askgod-server

  askgod-discourse:
    source: https://github.com/nsec/askgod-discourse
    source-type: git
    source-depth: 1
    plugin: go
    prime:
      - bin/askgod-discourse
