#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2013-2014 - Stéphane Graber <stgraber@nsec.io>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


# Imports
import sys
sys.path.insert(0, 'lib')

## Local modules
from askgod.config import config_get, config_get_int, config_load
from askgod.db import db_update_schema
from askgod.http_handler import CustomRequestHandler, CustomXMLRPCServer
from askgod.log import log_config
from askgod.rpc import AskGod

## External modules
from storm.locals import create_database

import argparse
import logging
import os

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="AskGod Server")
    parser.add_argument("--config", type=str, default="askgod.conf",
                        help="Config file (default: askgod.conf)")

    args = parser.parse_args()

    # Load the config
    config_load(args.config)

    for key in ('database_url',):
        if config_get("server", key, None) is None:
            parser.error("Missing required configuration variable '%s'" % key)

    # Configure logging
    log_config(config_get("server", "logfile", None),
               config_get("server", "loglevel", None))
    logging.info("Starting askgod")

    # Connect to the database
    database = create_database(config_get("server", "database_url"))
    db_update_schema(database)
    logging.debug("Connected to the database")

    # Start XMLRPC server
    net_addr = config_get("server", "net_addr", "")
    net_port = config_get_int("server", "net_port", 8080)
    server = CustomXMLRPCServer((net_addr, net_port),
                                CustomRequestHandler, False, True)
    server.database = database
    logging.info("Listening on: %s:%s" % (net_addr, net_port))
    server.register_instance(AskGod())

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        os._exit(0)
